server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Flutter Web routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # تمرير طلبات API إلى باكند Render
    location /api/ {
        proxy_pass https://holbertonschool-portfolio-project-22a6.onrender.com/api/;

        proxy_ssl_server_name on;
        proxy_set_header Host holbertonschool-portfolio-project-22a6.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 120s;
    }

    # منع تخزين ملف service worker القديم
    location = /flutter_service_worker.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        expires off;
        try_files $uri =404;
    }

    location = /version.json {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        expires off;
        try_files $uri =404;
    }

    # تخزين ملفات Flutter الثابتة
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|wasm)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}