enum FamilySettingsErrorCode {
  loadFamilyData,
  familyNameTooShort,
  invalidInvitationEmail,
  updateFamilyName,
  sendInvitation,
  acceptInvitation,
  rejectInvitation,
  invitedUserNotFound,
  cannotInviteYourself,
  userAlreadyInFamily,
  guardianTypeAlreadyExists,
  invitationAlreadyPending,
  familyNotFound,
  invalidEnteredData,
}
