import json
import os

from dotenv import load_dotenv
from langchain_openrouter import ChatOpenRouter

from app.agents.performance_schemas import (
    ChildPerformanceAnalysis,
)
from app.agents.strategy_schemas import (
    WeeklyPlanStrategy,
)


load_dotenv()


class StrategyAgent:
    def __init__(self):
        api_key = os.getenv("OPENROUTER_API_KEY")
        model_name = os.getenv("OPENROUTER_MODEL")

        if not api_key:
            raise ValueError("OPENROUTER_API_KEY is missing")

        if not model_name:
            raise ValueError("OPENROUTER_MODEL is missing")

        self.llm = ChatOpenRouter(
            model=model_name,
            api_key=api_key,
        )

        self.structured_llm = self.llm.with_structured_output(
            WeeklyPlanStrategy,
            include_raw=True,
        )

    def create_strategy(
        self,
        child_context,
        performance_analysis: ChildPerformanceAnalysis,
    ):
        prompt = self._build_prompt(
            child_context,
            performance_analysis,
        )

        response = self.structured_llm.invoke(prompt)

        result = response.get("parsed")
        parsing_error = response.get("parsing_error")

        if parsing_error:
            raise ValueError(
                f"StrategyAgent parsing failed: {parsing_error}"
            )

        if result is None:
            raise ValueError(
                "StrategyAgent failed to return structured output."
            )

        self._validate_strategy(
            result,
            performance_analysis,
        )

        return result

    def _build_prompt(
        self,
        child_context,
        performance_analysis,
    ):
        context_json = json.dumps(
            child_context,
            ensure_ascii=False,
            indent=2,
            default=str,
        )

        analysis_json = performance_analysis.model_dump_json(
            indent=2,
        )

        return f"""
You are the Weekly Planning Strategy Agent for Asalah.

You DO NOT choose actual tasks.

Your responsibility is only to design the strategy
for how the next weekly plan should be composed.

CHILD CONTEXT:
{context_json}

PERFORMANCE ANALYSIS:
{analysis_json}

The Performance Agent has already decided the
recommended number of tasks and weekly workload.

Your job is to determine:

1. How many tasks should come from the existing task bank.

2. How many tasks should be newly generated by AI.

3. How the tasks should be distributed across:
   RELIGIOUS
   FINANCIAL
   MORAL
   SOCIAL

4. What the primary focus of this week's plan should be.

5. What patterns or task types should be avoided.

Rules:

- total_tasks MUST equal
  performance_analysis.recommended_task_count.

- bank_tasks + generated_tasks MUST equal total_tasks.

- The sum of all category_distribution values
  MUST equal total_tasks.

- Do not create task titles or descriptions.

- Do not recommend specific tasks.

- Use the child's history and Performance Agent analysis.

- Weak categories may receive more attention,
  but the plan should not become completely unbalanced.

- Strong categories should still be represented
  when appropriate.

- If the child is a cold-start case,
  prefer a balanced distribution and avoid assuming
  strengths or weaknesses.

- The task bank should be used as a stable source
  of proven tasks, while AI-generated tasks should
  add personalization and variety.

- Do not assume information that does not appear
  in the child data.

- A weak category should normally receive gradual attention
  rather than being completely removed from the plan.

- If a category is weak, prefer assigning one easier task
  in that category unless there is strong evidence that the
  category should temporarily be excluded.

- Do not confuse a rejected task with a rejected category.
  Avoid repeating an unsuccessful task pattern, but you may
  approach the same category in a different way.

- Never invent time periods for historical totals.

- Do not claim that a recommendation came from the
  Performance Agent unless that recommendation actually
  appears in the provided Performance Analysis.

Return only the required structured strategy.
"""

    def _validate_strategy(
        self,
        strategy,
        performance_analysis,
    ):
        expected_total = (
            performance_analysis.recommended_task_count
        )

        if strategy.total_tasks != expected_total:
            raise ValueError(
                "Strategy total_tasks does not match "
                "PerformanceAgent recommendation."
            )

        source_total = (
            strategy.bank_tasks
            + strategy.generated_tasks
        )

        if source_total != strategy.total_tasks:
            raise ValueError(
                "bank_tasks + generated_tasks must equal total_tasks."
            )

        category_total = (
            strategy.category_distribution.RELIGIOUS
            + strategy.category_distribution.FINANCIAL
            + strategy.category_distribution.MORAL
            + strategy.category_distribution.SOCIAL
        )

        if category_total != strategy.total_tasks:
            raise ValueError(
                "Category distribution must equal total_tasks."
            )