"""add weekly plan proposals

Revision ID: 769e519f4482
Revises: 7977db2a19c6
Create Date: 2026-08-11 12:59:05.325047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769e519f4482'
down_revision = '7977db2a19c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plan_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_plan_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_plan_proposals_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_plan_proposals_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_plan_proposals_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_plan_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_plan_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_weekly_plan_proposals_created_by'))
        batch_op.drop_index(batch_op.f('ix_weekly_plan_proposals_child_id'))

    op.drop_table('weekly_plan_proposals')
    # ### end Alembic commands ###
