"""add avatar index to children

Revision ID: 7977db2a19c6
Revises: ed0896187639
Create Date: 2026-07-28 16:00:20.906968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7977db2a19c6'
down_revision = 'ed0896187639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_index', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_column('avatar_index')

    # ### end Alembic commands ###
