"""update database schema

Revision ID: c52729cbbf4b
Revises: ccdb9c930ae9
Create Date: 2026-07-15 04:23:26.091768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52729cbbf4b'
down_revision = 'ccdb9c930ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_date', sa.Date(), nullable=False))
        batch_op.create_unique_constraint('uq_daily_feedback_per_creator_per_day', ['child_id', 'created_by', 'feedback_date'])

    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_assignment_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('wishlist_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'wishlists', ['wishlist_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'task_assignments', ['task_assignment_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('wishlist_id')
        batch_op.drop_column('task_assignment_id')

    with op.batch_alter_table('daily_feedback', schema=None) as batch_op:
        batch_op.drop_constraint('uq_daily_feedback_per_creator_per_day', type_='unique')
        batch_op.drop_column('feedback_date')

    # ### end Alembic commands ###
