"""add child date index to task assignments

Revision ID: ed0896187639
Revises: c52729cbbf4b
Create Date: 2026-07-22 14:58:00.982678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0896187639'
down_revision = 'c52729cbbf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_task_assignments_child_date', ['child_id', 'assigned_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_task_assignments_child_date')

    # ### end Alembic commands ###
